export default function ThreeDPrintingPage() {
  return (
    <main className="bg-black text-white">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-black via-red-900 to-black py-20">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-4xl text-center">
            <h1 className="mb-6 text-5xl font-bold lg:text-6xl">
              3D{" "}
              <span className="bg-gradient-to-r from-red-500 to-red-600 bg-clip-text text-transparent">
                Printing
              </span>
            </h1>
            <p className="mb-8 text-xl text-gray-300 lg:text-2xl">
              Custom 3D models generated by AI. Upload a photo or describe what you want, and we&apos;ll bring it to life with professional 3D printing.
            </p>

            {/* Key Stats */}
            <div className="mb-12 grid grid-cols-1 gap-8 md:grid-cols-3">
              <div className="text-center">
                <div className="mb-2 text-4xl font-bold text-red-500">Text to 3D</div>
                <div className="text-gray-400">Upload a description or image</div>
              </div>
              <div className="text-center">
                <div className="mb-2 text-4xl font-bold text-red-500">Image to 3D</div>
                <div className="text-gray-400">Convert your photos</div>
              </div>
              <div className="text-center">
                <div className="mb-2 text-4xl font-bold text-red-500">No Minimums</div>
                <div className="text-gray-400">Order 1 piece or 10,000+</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3D Catalog Embed */}
      <section className="bg-gray-900 py-16">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-4xl font-bold text-white">3D Model Catalog</h2>
            <p className="text-xl text-gray-400">
              Browse our catalog of AI-generated 3D models. Select a model, choose your specifications, and get an instant quote.
            </p>
          </div>

          {/* Iframe embedding Sweatshop Swag catalog */}
          <div className="mx-auto max-w-7xl">
            <div className="mb-4 flex items-center justify-between bg-zinc-800 p-6 rounded-lg">
              <div className="flex items-center gap-3">
                <div className="h-3 w-3 rounded-full bg-red-600"></div>
                <div>
                  <h3 className="text-xl font-bold text-white">Powered by Meshy AI</h3>
                  <p className="text-gray-400 text-sm">Generate custom 3D models from text or images</p>
                </div>
              </div>
              <a
                href="https://sweatshopswag.com/3d-printing"
                target="_blank"
                rel="noopener noreferrer"
                className="text-red-500 hover:text-red-400 font-semibold"
              >
                Visit Full Catalog →
              </a>
            </div>

            <iframe
              src="https://sweatshopswag.com/3d-printing"
              className="w-full h-[800px] border-0 rounded-lg bg-black"
              title="3D Model Catalog"
              scrolling="yes"
            />
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="bg-black py-16">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-4xl font-bold text-white">How It Works</h2>
            <p className="text-xl text-gray-400">
              Three simple steps to get your custom 3D model printed and delivered
            </p>
          </div>

          <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
            <div className="border-gray-800 bg-zinc-900 p-6 rounded-lg">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-red-600/20">
                <span className="text-4xl font-bold text-red-500">1</span>
              </div>
              <h3 className="mb-2 text-xl font-bold text-white">Generate or Upload</h3>
              <p className="text-gray-400">
                Use our AI-powered 3D generator to create a model from scratch, or upload your own 3D file.
              </p>
            </div>

            <div className="border-gray-800 bg-zinc-900 p-6 rounded-lg">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-red-600/20">
                <span className="text-4xl font-bold text-red-500">2</span>
              </div>
              <h3 className="mb-2 text-xl font-bold text-white">Get Instant Quote</h3>
              <p className="text-gray-400">
                Select your model, material, and quantity. Receive an instant price quote with no hidden fees.
              </p>
            </div>

            <div className="border-gray-800 bg-zinc-900 p-6 rounded-lg">
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-red-600/20">
                <span className="text-4xl font-bold text-red-500">3</span>
              </div>
              <h3 className="mb-2 text-xl font-bold text-white">Print & Ship</h3>
              <p className="text-gray-400">
                We print your 3D model on industrial-grade equipment and ship it anywhere in Canada. Fast turnaround guaranteed.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="bg-gray-900 py-16">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-4xl font-bold text-white">3D Printing Pricing</h2>
            <p className="text-xl text-gray-400">
              Simple, transparent pricing based on model size and material. No minimums, volume discounts available.
            </p>
          </div>

          <div className="mx-auto max-w-4xl">
            <div className="overflow-hidden rounded-xl border border-gray-700">
              <table className="w-full">
                <thead className="bg-gray-800">
                  <tr>
                    <th className="px-6 py-4 text-left font-bold text-white">Size</th>
                    <th className="px-6 py-4 text-left font-bold text-white">Example</th>
                    <th className="px-6 py-4 text-right font-bold text-white">Starting Price</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-700">
                  <tr className="bg-gray-900 hover:bg-gray-800">
                    <td className="px-6 py-4 font-medium text-white">Small</td>
                    <td className="px-6 py-4 text-gray-400">Under 50mm</td>
                    <td className="px-6 py-4 text-right font-bold text-red-500">$15-25</td>
                  </tr>
                  <tr className="bg-gray-900 hover:bg-gray-800">
                    <td className="px-6 py-4 font-medium text-white">Medium</td>
                    <td className="px-6 py-4 text-gray-400">50-100mm</td>
                    <td className="px-6 py-4 text-right font-bold text-red-500">$35-50</td>
                  </tr>
                  <tr className="bg-gray-900 hover:bg-gray-800">
                    <td className="px-6 py-4 font-medium text-white">Large</td>
                    <td className="px-6 py-4 text-gray-400">100-150mm</td>
                    <td className="px-6 py-4 text-right font-bold text-red-500">$60-100</td>
                  </tr>
                  <tr className="bg-gray-900 hover:bg-gray-800">
                    <td className="px-6 py-4 font-medium text-white">XL</td>
                    <td className="px-6 py-4 text-gray-400">150-200mm</td>
                    <td className="px-6 py-4 text-right font-bold text-red-500">$100-150</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mt-4 text-center text-sm text-gray-500">
              * Volume discounts available for orders over 10 pieces. Contact us for custom sizes or special projects.
            </p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-gradient-to-br from-gray-900 to-black py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-4xl font-bold text-white">Ready to Get Started?</h2>
          <p className="mb-8 text-xl text-gray-300">
            Upload your design or select a model from our catalog. Get an instant quote and we&apos;ll print and ship your custom 3D model.
          </p>
          <a
            href="/contact"
            className="inline-flex items-center justify-center rounded-lg bg-red-600 px-12 py-4 text-lg font-bold text-white transition-colors hover:bg-red-700"
          >
            Get Instant 3D Quote
          </a>
        </div>
      </section>
    </main>
  );
}
